#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaskBuddi.Droid.Resource", IsApplication=true)]

namespace TaskBuddi.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::TaskBuddi.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::TaskBuddi.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070001
			public const int locCategoryDisplay = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int locCategoryValues = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int uiCompass = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiRotateGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiScrollGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiTiltGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomControls = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int useViewLifecycle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int zOrderOnTop = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000d
			public const int actionbar_grey = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f040014
			public const int common_signin_btn_text_dark = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int common_signin_btn_text_light = 2130968597;
			
			// aapt resource value: 0x7f04000e
			public const int darker = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int darker_mid = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int darker_more = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int lighter = 2130968593;
			
			// aapt resource value: 0x7f04000b
			public const int shadeygrey = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int tb_lightblue = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int tb_mainBg = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int tb_text = 2130968595;
			
			// aapt resource value: 0x7f04000c
			public const int tb_white = 2130968588;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_signin_btn_icon_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_disabled_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_focus_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_normal_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_pressed_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_disabled_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_focus_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_normal_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_pressed_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_2markers = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_addtask = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_delete = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_save = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_bigplus = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_bigplus2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_box_plus = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_box_ticked = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_box_unticked = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_checkmark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_launcher = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_marker = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_marker2 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_markershaded = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_markerthick = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_plus_thick = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_plusone_medium_off_client = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_plusone_small_off_client = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_plusone_standard_off_client = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_plusone_tall_off_client = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_trashShaded = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int tb_icon_bluebox = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int tb_whitesplit = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0010
			public const int catSpinner = 2131361808;
			
			// aapt resource value: 0x7f0a0018
			public const int checkmark = 2131361816;
			
			// aapt resource value: 0x7f0a001b
			public const int groupDetailCheckAll = 2131361819;
			
			// aapt resource value: 0x7f0a0015
			public const int groupDetailTasksList = 2131361813;
			
			// aapt resource value: 0x7f0a0019
			public const int homeGroupClickableFrame = 2131361817;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a000a
			public const int layoutMain = 2131361802;
			
			// aapt resource value: 0x7f0a000f
			public const int lblCat = 2131361807;
			
			// aapt resource value: 0x7f0a000b
			public const int lblGroup = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int lblName = 2131361805;
			
			// aapt resource value: 0x7f0a0011
			public const int lblNotes = 2131361809;
			
			// aapt resource value: 0x7f0a0006
			public const int listView1 = 2131361798;
			
			// aapt resource value: 0x7f0a0020
			public const int menu_add_taskGroup = 2131361824;
			
			// aapt resource value: 0x7f0a001f
			public const int menu_delete = 2131361823;
			
			// aapt resource value: 0x7f0a001e
			public const int menu_save = 2131361822;
			
			// aapt resource value: 0x7f0a0021
			public const int menu_show_map = 2131361825;
			
			// aapt resource value: 0x7f0a0014
			public const int newGroupName = 2131361812;
			
			// aapt resource value: 0x7f0a0013
			public const int newGroupView = 2131361811;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0008
			public const int snippet = 2131361800;
			
			// aapt resource value: 0x7f0a001d
			public const int taskListNotes = 2131361821;
			
			// aapt resource value: 0x7f0a000c
			public const int tdAssignedTo = 2131361804;
			
			// aapt resource value: 0x7f0a0012
			public const int tdNotes = 2131361810;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0007
			public const int title = 2131361799;
			
			// aapt resource value: 0x7f0a001c
			public const int vCheck = 2131361820;
			
			// aapt resource value: 0x7f0a0005
			public const int vFrame = 2131361797;
			
			// aapt resource value: 0x7f0a001a
			public const int vGroupName = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int vLayout = 2131361815;
			
			// aapt resource value: 0x7f0a0016
			public const int vMain = 2131361814;
			
			// aapt resource value: 0x7f0a0009
			public const int vMap = 2131361801;
			
			// aapt resource value: 0x7f0a000e
			public const int vName = 2131361806;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MapInfoWindow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MapLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TaskDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TaskGroupDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TaskGroupListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TaskListItem = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu_detailsscreen = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int menu_homescreen = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05001c
			public const int ApplicationName = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int Hello = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int app_name = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int auth_client_needs_enabling_title = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int auth_client_needs_installation_title = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int auth_client_needs_update_title = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int auth_client_play_services_err_notification_msg = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int auth_client_requested_by_msg = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int auth_client_using_bad_version_title = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_button = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_enable_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_text_phone = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_tablet = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_install_title = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_invalid_account_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_invalid_account_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_network_error_text = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_network_error_title = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_unknown_issue = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unsupported_date_text = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_unsupported_text = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_unsupported_title = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_update_button = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_text = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_update_title = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int common_signin_button_text = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int common_signin_button_text_long = 2131034131;
			
			// aapt resource value: 0x7f05001a
			public const int location_client_powered_by_google = 2131034138;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_TaskBuddi = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int groupDetail = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int groupTitleBoxSize = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int homeBoxSize = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int homeGroupTitle = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int homeGroupTitle_detail = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int homeTaskText = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int homeTaskText_done = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int homeTaskText_new = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int taskListNotes = 2131230731;
			
			// aapt resource value: 0x7f080001
			public const int tb_background = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int tb_notebackground = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] MapAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
